### ISSUE TITLE
Detect the linux kernel driver and emit a warning from libairspy

### ISSUE THREAD

**Issue by LazyDodo** [airspy/host#10]
Open fails due to the kernel driver having claimed the interface already, we should probably tell the user about this instead of exiting with a generic open error.

**Comment by bvernoux** [comment]
See fix in https://github.com/airspy/host/tree/linux_kernel_driver
Note:
With actual kernel driver (up to 4.0 ...) there is a problem to work with AirSpy Firmware > 0.9.9.
The kernel driver does not support them correctly 
see http://lxr.free-electrons.com/source/drivers/media/usb/airspy/airspy.c#L135 => #define BUF_SIZE 24 shall be modified to 128 in order to receive the full VERSION string else it returns an error and the kernel driver does not work like expected.
See also updated https://github.com/airspy/host/wiki/Troubleshooting especially to blacklist AirSpy Kernel driver for Kernel 3.17 or more.

**Comment by bvernoux** [comment]
Any test with latest trunk + Pull request #19 "Linux kernel driver support of libusb_detach_kernel_driver for Linux Kernel >= 3.17" is welcome in order to check this definitely fix this problem.

**Comment by bvernoux** [comment]
Merge pull request #19 from airspy/linux_kernel_driver
